# Workflow for publishing a release from a tag.
name: Publish Release From Tag

# Tags starting with "v" will trigger this workflow, i.e. "v1.0.0"
on:
  push:
    tags:
      - "v*"

  # Allow manual trigger of the workflow
  workflow_dispatch:

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# Cancel in-progress runs when a new run is queued.
concurrency:
  group: "publish-release-from-tag"
  cancel-in-progress: true

jobs:
  publish-release-from-tag:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    environment: github-pages
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # https://github.com/ghalactic/github-release-from-tag
      - name: Publish release
        uses: ghalactic/github-release-from-tag@v5
